# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publicacion', models.DateTimeField(auto_created=True)),
                ('titular', models.CharField(max_length=150)),
                ('sumilla', models.CharField(blank=True, default='', max_length=300)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
